Admin endpoints
ZsomborHajzer/DataProcessing-BackEnd pull request #12
Opened 2024-01-20 22:16 UTC by MartinezNicanor

2024-01-20 22:45 UTC, ZsomborHajzer requested changes
these changes i commented on are necessary

2024-01-20 22:45 UTC, ZsomborHajzer commented on src/routes/admin.ts
> +router.get('/juniorView', (req: Request, res : Response) => getMediorView(req, res));
Change to /mediorView

2024-01-20 22:45 UTC, ZsomborHajzer commented on src/routes/admin.ts
> +router.get('/juniorView', (req: Request, res : Response) => getJuniorView(req, res));
add middleware routes to juniorView, mediorView and seniorView like : 

router.get('/juniorView', allowJuniorMediorSenior,(req: Request, res : Response) => getJuniorView(req, res));

2024-01-20 22:45 UTC, ZsomborHajzer commented on src/controller/admin.ts
> +    if (req.user?.user_type !== 'Medior') {
if you apply middlewares on the routs directly (explained in comments for routes/admin file) this if statement  can be deleted

2024-01-20 22:45 UTC, ZsomborHajzer commented on src/controller/admin.ts
> +    if (req.user?.user_type !== 'Senior') {
same here if statement can be deleted if middlewares are applied

2024-01-20 22:45 UTC, ZsomborHajzer commented on src/controller/admin.ts
> +    if (req.user?.user_type !== 'Junior') {
if you apply middlewares on the routs directly (explained in comments for routes/admin file) this if statement can be deleted

2024-01-20 22:46 UTC, ZsomborHajzer commented on src/controller/admin.ts
> +    if (req.user?.user_type !== 'Medior') {
the comment explaining  this is the one above

2024-01-21 13:59 UTC, JoeyKraemer approved these changes

2024-01-21 14:00 UTC, JoeyKraemer approved these changes, later dismissed

2024-01-21 14:01 UTC, JoeyKraemer commented
LGMT!

2024-01-21 17:18 UTC, ZsomborHajzer approved these changes

2024-01-21 17:19 UTC, merged